import { Inter } from 'next/font/google'
import './globals.css'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ReduxStoreProvider from '@/redux/provider';
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ReduxStoreProvider>
    <html lang="en">
      <body className={inter.className}>
      <ToastContainer/>
        {children}
        </body>
    </html>
    </ReduxStoreProvider>
  )
}
